// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADS8gQ9tzD37MvKMdf11mM4h8iCt8KN1I',
    appId: '1:530402648661:web:4b9190559bf943340a6adc',
    messagingSenderId: '530402648661',
    projectId: 'swiggy-application-2aaf1',
    authDomain: 'swiggy-application-2aaf1.firebaseapp.com',
    storageBucket: 'swiggy-application-2aaf1.firebasestorage.app',
    measurementId: 'G-P1XWPFCS8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7WUqh1s9mGTG9GBK2hSmhi-BIv8JqmeE',
    appId: '1:530402648661:android:27588e515c0729610a6adc',
    messagingSenderId: '530402648661',
    projectId: 'swiggy-application-2aaf1',
    storageBucket: 'swiggy-application-2aaf1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAALiFYhQduD7LealdO5sSWv9lXQ1PoDAA',
    appId: '1:530402648661:ios:79980937a25e97f70a6adc',
    messagingSenderId: '530402648661',
    projectId: 'swiggy-application-2aaf1',
    storageBucket: 'swiggy-application-2aaf1.firebasestorage.app',
    iosBundleId: 'com.example.swiggyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAALiFYhQduD7LealdO5sSWv9lXQ1PoDAA',
    appId: '1:530402648661:ios:79980937a25e97f70a6adc',
    messagingSenderId: '530402648661',
    projectId: 'swiggy-application-2aaf1',
    storageBucket: 'swiggy-application-2aaf1.firebasestorage.app',
    iosBundleId: 'com.example.swiggyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADS8gQ9tzD37MvKMdf11mM4h8iCt8KN1I',
    appId: '1:530402648661:web:7aa217bfee1654800a6adc',
    messagingSenderId: '530402648661',
    projectId: 'swiggy-application-2aaf1',
    authDomain: 'swiggy-application-2aaf1.firebaseapp.com',
    storageBucket: 'swiggy-application-2aaf1.firebasestorage.app',
    measurementId: 'G-8BEN11HYP7',
  );
}
